# Site settings
title: /spk/dev
email: skrdev@ukr.net
description: > # this means to ignore newlines until "baseurl:"
  This is under construction. Something meanigfull will be here soon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spkps.github.io" # the base hostname & protocol for your site
twitter_username: spkps
github_username:  spkps

# Build settings
markdown: kramdown

collections:
    - gaetips
